# lint - checks syntax, code spelling, code indentation
# What's your goal for your workflow :
# Whenever someone changes the python code,
# Ther linter checks if syntax, format, indentation is correct or not

name: Auto Linter

on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      # This step will automatically clone the code of the current branch into the runner
      - name: Checkout/clone the code
        # we use "uses: actions/checkout@v7" for cloning the files/folders etc..
        uses: actions/checkout@v7

        # This step will install the linting tool
      - name: Install linter
        run: pip install ruff

        # This step will run the linter
      - name: Check the files for linting
        run: ruff check .
